spring.application.name=backend
server.port=8000

# DataSource
spring.datasource.url=jdbc:postgresql://db:5432/postgres
# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JWT Configuration
jwt.secret=kbfkbkfjbakfbvkdvasdfasdfasdffddfsfsdfsdfaadsfacxzcefds
jwt.expiration=30m
# Crypto
db.encryption.key=mySuperSecretKey

# Actuator Configuration
# management.endpoints.web.exposure.include=health,prometheus,metrics,info,jfr,custom,heapdump
management.endpoints.web.exposure.include=health,prometheus,metrics,info,custom
management.prometheus.metrics.export.enabled=true

# HTTP-metrics settings
management.metrics.enable.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms,300ms,500ms,1s,3s,5s

# extra HTTP-metrics
management.metrics.enable.process.files=true
management.metrics.enable.jvm=true

# Security
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=1q2w3e4r
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=alias
server.ssl.enabled=true

